config/routes.rb
Rails.application.routes.draw do

    get 'favorites/create'
    get 'favorites/destroy'
	root 'home#top'

	namespace :admin do
		resources :blogs, only: [:index, :new, :create, :show, :edit, :update]
	end
	namespace :admin do
    	resources :users, only: [:index, :show, :edit, :update]
	end
	namespace :admin do
    	resources :genres, only: [:index, :create, :edit, :update]
	end
	namespace :admin do
    	root 'home#top'
	end

	get 'home/about'
	get 'users/confirm'
	devise_for :admins, controllers: {sessions: 'admins/sessions'}
	devise_for :users

	resources :blogs, only: [:index, :show, :edit, :new, :create, :destroy] do
			resource :favorites, only: [:create, :destroy]
			resource :blog_comments, only: [:create]
	end
	resources :users, only: [:index, :show, :edit, :update, :search]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user
	has_many :blog_comments, dependent: :destroy
	attachment :image
	belongs_to :genre
	has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          Favorite.where(user_id: user.id).exists?
        end
    validates :title, presence: true
	validates :introduction, presence: true, length: {maximum: 200}
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
	belongs_to :user
    belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :blog
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  attachment :profile_image
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: {in:1..20}
  validates :email, presence: true
  validates :password, presence: true, length: {in:6..20}, on: :create
  validates :telephone, presence: true
  validates :introduction, presence: true

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController

	before_action :authenticate_admin! , only:[:top]


	def top
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		case resource
		when Admin
			admin_root_path
		when User
			root_path
		end
	end

	def after_sign_out_path_for(resource)
		case resource
		when :admin
			new_admin_session_path
		when :user
			root_path
		end
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :telephone, :introduction])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
	end
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController

	def create
		blog = Blog.find(params[:blog_id])
	    comment = current_user.blog_comments.new(blog_comment_params)
	    comment.blog_id = blog.id
	    comment.save
	    redirect_to blog_path(blog)
	end

	private
	def blog_comment_params
		params.require(:blog_comment).permit(:comment)
	end

	def blog_params
      	params.require(:blog).permit(:title,:introduction,:image,:genres_id)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user! , only:[:edit, :show]

  def index
    @blog = Blog.new
    if params[:query].present?
      genre_ids = Genre.where('name LIKE ?', "%#{params[:query]}%").pluck(:id)
      @blogs = Blog.where(genre_id: genre_ids).page(params[:page]).per(5)
    else
      @blogs = Blog.all.page(params[:page]).per(5)
    end
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
    @genre = @blog.genre
  end

  def create
    @blog = Blog.new(blog_params)
    @blogs = Blog.all
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog)
      @user = current_user
    else
      render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.new
    if @blog.save
      redirect_to blog_path(@blog)
     else
       @user = current_user
       render 'index'
    end
  end

  def new
    @blog = Blog.new
  end

  def destroy
      blog = Blog.find(params[:id])
      blog.destroy
      redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title,:introduction,:image,:genre_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
		blog = Blog.find(params[:blog_id])
        favorite = current_user.favorites.new(blog_id: blog.id)
        favorite.save
        redirect_back(fallback_location: root_path)
	end

	def destroy
		blog = Blog.find(params[:blog_id])
        favorite = current_user.favorites.find_by(blog_id: blog.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      if User.find(current_user.id).status == false
        sign_out_and_redirect(current_user)
      end
    end
  end

  def creare
    @blog = Blog.new(blog_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @blogs = Blog.all
    @blog.user_id = current_user.id
    if @blog.save #入力されたデータをdbに保存する。
      redirect_to blog_path(@blog), notice: "successfully created book!"#保存された場合の移動先を指定。
    else
      @user = current_user
      render 'index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user! , only:[:edit, :show, :confirm]

  def new
  	@user = User.new
  end

  def index
    @users = User.all.page(params[:page]).per(5)
    @user = User.find(current_user.id)
    @blog = Blog.new
  end

  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end

  def edit
    @user = User.find(params[:id])
      if current_user.id != @user.id
      redirect_to edit_user_path(current_user)
      end
  end

  def update
    @user = User.find(params[:id])
    if params[:status] == "false"
      @user.update_columns(status: false)
      sign_out_and_redirect(current_user)
    else
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to user_path(@user.id)
      else
        render :edit
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :introduction, :telephone, :password, :status, :profile_image)
  end

end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/home/_header.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
          <h2>カーナビー・ストーリー</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
          <ul class="nav pull-right nav-pills">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if admin_signed_in? %>
            <li class="nav-item <%= 'current' if current_page?(admin_root_path) %>"><%= link_to ' ホーム ', admin_root_path %></li>
            <li class="nav-item <%= 'current' if current_page?(admin_users_path) %>"><%= link_to ' 会員管理 ', admin_users_path %></li>
            <li class="nav-item <%= 'current' if current_page?(admin_blogs_path) %>"><%= link_to ' ブログ管理' , admin_blogs_path %></li>
            <li class="nav-item <%= 'current' if current_page?(admin_genres_path) %>"><%= link_to ' ジャンル管理 ', admin_genres_path %></li>
            <li class="nav-item <%= 'current' if current_page?(destroy_admin_session_path) %> pull-right"><%= link_to ' ログアウト ', destroy_admin_session_path, method: :delete %></li>
            <% else %>
            <li class="nav-item <%= 'current' if current_page?(admin_root_path) %>"><%= link_to ' ホーム', admin_root_path %></li>
            <li class="nav-item <%= 'current' if current_page?(new_admin_session_path) %>"><%= link_to ' ログイン', new_admin_session_path %></li>
            <% end %>
          </ul>
      </div>
    </div>
</div>

app/views/admin/home/top.html.erb
<%= render "admin/home/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<h2>管理者ページ</h2>
		</div>
	</div>
</div>

app/views/home/about.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-7 col-md-offset-2">

			<h2>当サイトについて</h2>

			<p>
				「若者だって車は好きだし発信したい」
				<br><br>
				”若者の車離れ”と耳にすることが増えてきておりますが、<br>
				決して若者が車への興味が無くなったわけではありません。<br>
				車好きの若者はSNSで検索するとたくさん車について語っておりますし、<br>
				車を買うために一生懸命働いたり貯金したりしています。<br>
				車は欲しい。だけど、経済的に余裕がない」人はいっぱいいます。<br>
				そこで、車は買えないけど好きな車を紹介してユーザー同士「好きをシェア」するコミュニティサイトを作り、<br>
				語り合いの場を与えられたらなと思い、サイトを立ち上げました。
			</p>

		</div>
	</div>
</div>

app/views/home/top.html.erb
<%= render "users/header" %>

<div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2" style="margin-top: 50px;">
			 <div id="theTarget">
			    <div class="image1"></div>
			    <div class="image2"></div>
			    <div class="image3"></div>
			    <div class="image4"></div>
			    <div class="image5"></div>
			 </div>
		</div>
	</div>
</div>