config/routes.rb
Rails.application.routes.draw do

    get 'favorites/create'
    get 'favorites/destroy'
	root 'home#top'

	namespace :admin do
		resources :blogs, only: [:index, :new, :create, :show, :edit, :update]
	end
	namespace :admin do
    	resources :users, only: [:index, :show, :edit, :update]
	end
	namespace :admin do
    	resources :genres, only: [:index, :create, :edit, :update]
	end
	namespace :admin do
    	root 'home#top'
	end

	get 'home/about'
	get 'users/confirm'
	devise_for :admins, controllers: {sessions: 'admins/sessions'}
	devise_for :users

	resources :blogs, only: [:index, :show, :edit, :new, :create, :destroy] do
			resource :favorites, only: [:create, :destroy]
			resource :blog_comments, only: [:create]
	end
	resources :users, only: [:index, :show, :edit, :update, :search]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user
	has_many :blog_comments, dependent: :destroy
	attachment :image
	belongs_to :genre
	has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          Favorite.where(user_id: user.id).exists?
        end
    validates :title, presence: true
	validates :introduction, presence: true, length: {maximum: 200}
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
	belongs_to :user
    belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :blog
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  attachment :profile_image
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: {in:1..20}
  validates :email, presence: true
  validates :password, presence: true, length: {in:6..20}, on: :create
  validates :telephone, presence: true
  validates :introduction, presence: true

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController

	before_action :authenticate_admin! , only:[:top]


	def top
	end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

	before_action :authenticate_admin! , only:[:index, :show, :edit]

  def index
    @users = User.all.page(params[:page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to admin_user_path(params[:id])
  	else
  		render "admin/users/edit"
  	end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :telephone, :password, :status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		case resource
		when Admin
			admin_root_path
		when User
			root_path
		end
	end

	def after_sign_out_path_for(resource)
		case resource
		when :admin
			new_admin_session_path
		when :user
			root_path
		end
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :telephone, :introduction])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
	end
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController

	def create
		blog = Blog.find(params[:blog_id])
	    comment = current_user.blog_comments.new(blog_comment_params)
	    comment.blog_id = blog.id
	    comment.save
	    redirect_to blog_path(blog)
	end

	private
	def blog_comment_params
		params.require(:blog_comment).permit(:comment)
	end

	def blog_params
      	params.require(:blog).permit(:title,:introduction,:image,:genres_id)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user! , only:[:edit, :show]

  def index
    @blog = Blog.new
    if params[:query].present?
      genre_ids = Genre.where('name LIKE ?', "%#{params[:query]}%").pluck(:id)
      @blogs = Blog.where(genre_id: genre_ids).page(params[:page]).per(5)
    else
      @blogs = Blog.all.page(params[:page]).per(5)
    end
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
    @genre = @blog.genre
  end

  def create
    @blog = Blog.new(blog_params)
    @blogs = Blog.all
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog)
      @user = current_user
    else
      render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.new
    if @blog.save
      redirect_to blog_path(@blog)
     else
       @user = current_user
       render 'index'
    end
  end

  def new
    @blog = Blog.new
  end

  def destroy
      blog = Blog.find(params[:id])
      blog.destroy
      redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title,:introduction,:image,:genre_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
		blog = Blog.find(params[:blog_id])
        favorite = current_user.favorites.new(blog_id: blog.id)
        favorite.save
        redirect_back(fallback_location: root_path)
	end

	def destroy
		blog = Blog.find(params[:blog_id])
        favorite = current_user.favorites.find_by(blog_id: blog.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      if User.find(current_user.id).status == false
        sign_out_and_redirect(current_user)
      end
    end
  end

  def creare
    @blog = Blog.new(blog_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @blogs = Blog.all
    @blog.user_id = current_user.id
    if @blog.save #入力されたデータをdbに保存する。
      redirect_to blog_path(@blog), notice: "successfully created book!"#保存された場合の移動先を指定。
    else
      @user = current_user
      render 'index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user! , only:[:edit, :show, :confirm]

  def new
  	@user = User.new
  end

  def index
    @users = User.all.page(params[:page]).per(5)
    @user = User.find(current_user.id)
    @blog = Blog.new
  end

  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end

  def edit
    @user = User.find(params[:id])
      if current_user.id != @user.id
      redirect_to edit_user_path(current_user)
      end
  end

  def update
    @user = User.find(params[:id])
    if params[:status] == "false"
      @user.update_columns(status: false)
      sign_out_and_redirect(current_user)
    else
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to user_path(@user.id)
      else
        render :edit
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :introduction, :telephone, :password, :status, :profile_image)
  end

end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= render "admin/home/header" %>

<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">

		<%= form_for @user,url: admin_user_path(@user.id) do |f| %>
		<%= render "devise/shared/error_messages", resource: @user %>

		<div class="row">
			<div class="col-md-5 col-md-offset-1">
				<h3 class="admin-user-edit-title">会員編集画面</h3>
			</div>
		</div>

		<div class="row admin-user-edit-row">
			<div class="col-md-2 col-md-offset-1">
				<p>会員ID</p>
			</div>
			<div class="col-md-1">
				<p><%= @user.id %></p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-4 col-md-offset-1">
				<p>ハンドルネーム</p>
			</div>
			<div class="col-md-1">
				<%= f.text_field :name, class: "panel panel-default" %>
			</div>
		</div>

		<div class="row">
			<div class="col-md-4 col-md-offset-1">
				<p>電話番号</p>
			</div>
			<div class="col-md-1">
				<%= f.text_field :telephone, class: "panel panel-default" %>
			</div>
		</div>

		<div class="row">
			<div class="col-md-4 col-md-offset-1">
				<p>メールアドレス</p>
			</div>
			<div class="col-md-1">
				<%= f.text_field :email, class: "panel panel-default" %>
			</div>
		</div>
		<div class="row"><p> </p></div>

		<div class="row">
	    	<div class="col-md-5 col-md-offset-1">プロフィール画像</div>
	        <div class="col-md-2">
	        	<%= attachment_image_tag @user, :profile_image, :fill, 200,200, id: "attachment-image" %>
				<%= f.attachment_field :profile_image, direct: true, class: "edit-attachment",id: "click-attachment" %>
			</div>
	    </div>

		<div class="row admin-user-edit-row">
			<div class="col-md-4 col-md-offset-1">
				<p>会員ステータス</p>
			</div>
			<div class="col-md-4">
				<span><%= f.radio_button :status, true %>有効</span>
				<span><%= f.radio_button :status, false %>退会済み</span>
			</div>
		</div>

		<div class="row admin-user-edit-row">
			<div class="col-md-2 col-md-offset-1">
				<%= f.submit "変更を保存する", class: "btn btn-primary" %>
			</div>
		</div>

		<% end %>
		</div>
	</div>
</div>

app/views/admin/users/index.html.erb
<%= render "admin/home/header" %>


<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
			<h3>会員一覧画面</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<table class="table">
						<tr>
							<th>会員ID</th>
							<th>氏名</th>
							<th>メールアドレス</th>
							<th>ステータス</th>
						</tr>
					<tbody class="table-box">
						<% @users.each do |user| %>
							<tr>
								<td><%= user.id %></td>
								<td>
									<%= link_to user.name, admin_user_path(user.id) %>
								</td>
								<td><%= user.email %></td>
								<td>
									<%= user.status == true ? "有効" : "無効" %>
								</td>
							</tr>
						<% end %>
					</tbody>
			</table>

			<div class="paginate">
      			<%= paginate @users %>
    		</div>

		</div>
	</div>

</div>

app/views/admin/users/show.html.erb
<%= render 'admin/home/header' %>

<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">

        <h3 class="title">会員詳細画面</h3>

        <div class="row text">
          <div class="col-md-4">顧客ID</div>
          <div class="col-md-4"><%= @user.id %>
            <% if @user.status == true %>
              <span class="status-label-true">有効会員</span>
            <% else %>
              <span class="status-label-false">無効会員</span>
            <% end %>
          </div>
        </div>

        <div class="row text">
          <div class="col-md-4">氏名</div>
          <div class="col-md-3"><%= @user.name %></div>
        </div>

        <div class="row text">
          <div class="col-md-4">電話番号</div>
          <div class="col-md-1"><%= @user.telephone %></div>
        </div>

        <div class="row text">
          <div class="col-md-4">メールアドレス</div>
          <div class="col-md-1"><%= @user.email %></div>
        </div>

        <div class="row text">
          <div class="col-md-4">プロフィール画像</div>
          <div class="col-md-7"><%= attachment_image_tag @user, :profile_image, :fill, 200,200, fallback: "no-image-mini.jpg", id: "attachment-image" %>
          </div>
        </div>

        <div class="row bottan-box">
            <div class="col-md-2">
            <%= link_to "編集する", edit_admin_user_path, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
  </div>
<div>

app/views/users/_header.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
          <h2>カーナビー・ストーリー</h2>
      </div>

      <div class="col-md-4 col-md-offset-2">
        <% if user_signed_in? %>
          <h3>メーカー検索</h3>

          <%= form_with url: blogs_path, method: :get, local: true do |f| %>
              <%= f.text_field :query %>
              <%= f.submit :search %>
          <% end %>
        <% end %>
      </div>



    <div class="row">
      <div class="col-md-8 col-md-offset-2">
          <ul class="nav pull-right nav-pills">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li class="nav-item <%= 'current' if current_page?(root_path) %>"><%= link_to ' HOME', root_path, data: {"turbolinks" => false} %></li>
            <li class="nav-item <%= 'current' if current_page?(home_about_path) %>"><%= link_to ' ABOUT', home_about_path %></li>
            <li class="nav-item <%= 'current' if current_page?(users_path) %>"><%= link_to ' USERS', users_path %></li>
            <li class="nav-item <%= 'current' if current_page?(blogs_path) %>"><%= link_to ' BLOGS', blogs_path %></li>
            <li class="nav-item"><%= link_to ' YOUTUBE', 'https://www.youtube.com/' %></li>
            <li class="nav-item <%= 'current' if current_page?(user_path(current_user)) %>"><%= link_to ' MY PAGE', user_path(current_user) %></li>
            <li class="nav-item <%= 'current' if current_page?(new_blog_path) %>"><%= link_to ' 投稿 ', new_blog_path %></li>
            <li class="nav-item <%= 'current' if current_page?(destroy_user_session_path) %> pull-right"><%= link_to ' LOGOUT', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li class="nav-item <%= 'current' if current_page?(root_path) %>"><%= link_to ' HOME', root_path %></li>
            <li class="nav-item <%= 'current' if current_page?(home_about_path) %>"><%= link_to ' ABOUT', home_about_path %></li>
            <li class="nav-item "><%= link_to ' YOUTUBE', 'https://www.youtube.com/' %></li>
            <li class="nav-item <%= 'current' if current_page?(new_user_registration_path) %>"><%= link_to ' SIGN UP', new_user_registration_path, data: {"turbolinks" => false} %></li>
            <li class="nav-item <%= 'current' if current_page?(new_user_session_path) %>"><%= link_to ' LOGIN', new_user_session_path, data: {"turbolinks" => false} %></li>
            <% end %>
          </ul>
      </div>
    </div>
</div>

app/views/users/confirm.html.erb
<div class="confirm-main" style="margin-top: 100px; text-align: center">
	<div class="confirm-main-title">
		<h3>本当に退会しますか？</h3>
	</div>
		<br>
		<div class="confirm-text">
			<h3>退会すると、会員登録情報や<br>
				これまでのブログ履歴が閲覧できなくなります。<br>
				退会する場合は、「退会する」をクリックしてください。</h3>
		</div>
		<br>
    		<%= link_to '退会しない',user_path(current_user), class: "btn btn-lg btn-primary"%>
   			<%= link_to '退会する',user_path(current_user.id, status: false), method: :patch, class: "btn btn-lg btn-danger" %>

</div>

app/views/users/edit.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">

			<h2>会員情報編集</h2>

			<%= form_for(@user) do |f| %>

				<!-- エラーメッセージ表示-->
				    <% if @user.errors.any? %>
				        <%= @user.errors.count %>error prohibited this obj from being saved
				        <%= @user.errors.full_messages.each do |message| %>
							<%= message %>
				        <% end %>
				    <% end %>

				<!-- エラーメッセージ表示-->
				<div class="row">
					<div class="col-md-4 col-md-offset-1">ハンドルネーム</div>
					<div class="col-md-2"><%= f.text_field :name, class: "panel panel-default"  %></div>
				</div>

				<div class="row">
					<div class="col-md-4 col-md-offset-1">自己紹介</div>
					<div class="col-md-2"><%= f.text_area :introduction, class: "panel panel-default"  %></div>
				</div>

				<div class="row">
	      			<div class="col-md-4 col-md-offset-1">メールアドレス</div>
	        			<div class="col-md-2"><%= f.email_field :email, autocomplete: "email", class: "panel panel-default"  %></div>
	    		</div>

	    		<div class="row">
			      <div class="col-md-5 col-md-offset-1">電話番号(ハイフンなし)</div>
			        <div class="col-md-2"><%= f.telephone_field :telephone, class: "panel panel-default"  %></div>
			    </div>

			    <div class="row">
			    	<div class="col-md-5 col-md-offset-1">プロフィール画像</div>
			        <div class="col-md-2">
			        	<%= attachment_image_tag @user, :profile_image, :fill, 200,200, id: "attachment-image" %>
						<%= f.attachment_field :profile_image, direct: true, class: "edit-attachment",id: "click-attachment" %>
					</div>
			    </div>

				<div class="row" style="margin-top: 20px;">
					<div class="col-md-12 col-md-offset-1">
				    	<div class="row bttan">
				    		<div class="col-md-5 col-md-offset-1">
				        		<%= f.submit "編集内容を保存する", class: "btn btn-primary btn-block" %>
				      		</div>
				      		<div class="col-md-5 col-md-offset-">
				        		<%= link_to "退会する", users_confirm_path, class: "btn btn-danger btn-block" %>
				    		</div>
						</div>
				    </div>
				 </div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<h2>会員一覧</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-md-7 col-md-offset-2">
			<table class="table">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th>名前</th>
						<th>自己紹介</th>
						<th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><td>
						<td><%= user.name %></td>
						<td><%= user.introduction %></td>
						<td><%= link_to "詳細", user, class: "user_#{user.id}" %></td>
					<% end %>
				</tbody>
			</table>
			<div class="paginate">
    			<%= paginate @users %>
    		</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<h2>マイページ</h2>

			<h4 class="mypage-headline-4l">登録情報</h4>
			<% if current_user == @user %>
				<%= link_to "編集する", edit_user_path(current_user), class: 'btn btn-primary active' %>
				<%= link_to "パスワードを変更する", edit_user_password_path, class: 'btn btn-primary active' %>
			<% end %>
			<table class="table table-bordered">
				<tbody class="profile-list">
					<tr>
						<th class="profile-list-title active col-md-2">プロフィール画像</th>
						<td class="col-md-7"><%= attachment_image_tag @user, :profile_image, :fill, 200,200, fallback: "no-image-mini.jpg", id: "attachment-image" %></td>
					</tr>

					<tr>
						<th class="profile-list-title active col-md-2">氏名</th>
						<td class="col-md-7"><%= "#{@user.name}" %></td>
					</tr>

					<tr>
						<th class="profile-list-title active col-md-3">自己紹介</th>
						<td class="col-md-7"><%= "#{@user.introduction}" %></td>
					</tr>

				<% if current_user == @user %>

					<tr>
						<th class="profile-list-title active col-md-3">メールアドレス</th>
						<td class="col-md-7"><%= "#{@user.email}" %></td>
					</tr>

					<tr>
						<th class="profile-list-title active col-md-2">電話番号</th>
						<td class="col-md-7"><%= "#{@user.telephone}" %></td>
					</tr>
				<% end %>

				</tbody>
			</table>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>タイトル</th>
						<th>紹介文</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @blogs.each do |blog| %>
					<tr>
						<td class="col-md-1 col-md-offset-4">
							<%= link_to (blog.user) do %>
							<%= attachment_image_tag(blog.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td class="col-md-3 col-md-offset-4"><%= link_to blog.title,blog, class: "blog_#{blog.id}" %></td>
						<td class="col-md-3 col-md-offset-4"><%= blog.introduction %></td>
						<td class="col-md-1 col-md-offset-2">
							<% if blog.favorited_by?(current_user) %>
							    <%= link_to blog_favorites_path(blog),class: 'glyphicon glyphicon-heart', method: :delete do %>
							      <i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
							      <%= blog.favorites.count %>
							    <% end %>
							<% else %>
							    <%= link_to blog_favorites_path(blog),class: 'glyphicon glyphicon-heart', method: :post do %>
							      <i class="fa fa-heart-o" aria-hidden="true"></i>
							      <%= blog.favorites.count %>
							 <% end %>
						<% end %>
						</td>
						<td>
						    <i class="col-md-6 col-md-offset-3 comment-count">コメント数：<%= blog.blog_comments.count %></i>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
 </div>