config/routes.rb
Rails.application.routes.draw do

    get 'favorites/create'
    get 'favorites/destroy'
	root 'home#top'

	namespace :admin do
		resources :blogs, only: [:index, :new, :create, :show, :edit, :update]
	end
	namespace :admin do
    	resources :users, only: [:index, :show, :edit, :update]
	end
	namespace :admin do
    	resources :genres, only: [:index, :create, :edit, :update]
	end
	namespace :admin do
    	root 'home#top'
	end

	get 'home/about'
	get 'users/confirm'
	devise_for :admins, controllers: {sessions: 'admins/sessions'}
	devise_for :users

	resources :blogs, only: [:index, :show, :edit, :new, :create, :destroy] do
			resource :favorites, only: [:create, :destroy]
			resource :blog_comments, only: [:create]
	end
	resources :users, only: [:index, :show, :edit, :update, :search]
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

	belongs_to :user
	has_many :blog_comments, dependent: :destroy
	attachment :image
	belongs_to :genre
	has_many :favorites, dependent: :destroy
        def favorited_by?(user)
          Favorite.where(user_id: user.id).exists?
        end
    validates :title, presence: true
	validates :introduction, presence: true, length: {maximum: 200}
end

app/models/blog_comment.rb
class BlogComment < ApplicationRecord
	belongs_to :user
    belongs_to :blog
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
    belongs_to :blog
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  attachment :profile_image
  has_many :blog_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: {in:1..20}
  validates :email, presence: true
  validates :password, presence: true, length: {in:6..20}, on: :create
  validates :telephone, presence: true
  validates :introduction, presence: true

end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController

  before_action :authenticate_admin! , only:[:index, :show, :edit]

  def index
    @blogs = Blog.all.page(params[:page]).per(5)
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def update
    @blog = Blog.new
    if @blog.update(blog_params)
      redirect_to admin_blogs_path(@blog)
     else
       @user = current_user
       render 'admin/blogs/index'
    end
  end

  def destroy
      blog = Blog.find(params[:id])
      blog.destroy
      redirect_to admin_blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title,:introduction,:image,:genre_id)
    end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController

	before_action :authenticate_admin! , only:[:top]


	def top
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		case resource
		when Admin
			admin_root_path
		when User
			root_path
		end
	end

	def after_sign_out_path_for(resource)
		case resource
		when :admin
			new_admin_session_path
		when :user
			root_path
		end
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :telephone, :introduction])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :password])
	end
end

app/controllers/blog_comments_controller.rb
class BlogCommentsController < ApplicationController

	def create
		blog = Blog.find(params[:blog_id])
	    comment = current_user.blog_comments.new(blog_comment_params)
	    comment.blog_id = blog.id
	    comment.save
	    redirect_to blog_path(blog)
	end

	private
	def blog_comment_params
		params.require(:blog_comment).permit(:comment)
	end

	def blog_params
      	params.require(:blog).permit(:title,:introduction,:image,:genres_id)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :authenticate_user! , only:[:edit, :show]

  def index
    @blog = Blog.new
    if params[:query].present?
      genre_ids = Genre.where('name LIKE ?', "%#{params[:query]}%").pluck(:id)
      @blogs = Blog.where(genre_id: genre_ids).page(params[:page]).per(5)
    else
      @blogs = Blog.all.page(params[:page]).per(5)
    end
    @users = User.all
    @user = User.find(current_user.id)
  end

  def show
    @blog = Blog.find(params[:id])
    @blog_comment = BlogComment.new
    @genre = @blog.genre
  end

  def create
    @blog = Blog.new(blog_params)
    @blogs = Blog.all
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog)
      @user = current_user
    else
      render 'new'
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.new
    if @blog.save
      redirect_to blog_path(@blog)
     else
       @user = current_user
       render 'index'
    end
  end

  def new
    @blog = Blog.new
  end

  def destroy
      blog = Blog.find(params[:id])
      blog.destroy
      redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title,:introduction,:image,:genre_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
		blog = Blog.find(params[:blog_id])
        favorite = current_user.favorites.new(blog_id: blog.id)
        favorite.save
        redirect_back(fallback_location: root_path)
	end

	def destroy
		blog = Blog.find(params[:blog_id])
        favorite = current_user.favorites.find_by(blog_id: blog.id)
        favorite.destroy
        redirect_back(fallback_location: root_path)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      if User.find(current_user.id).status == false
        sign_out_and_redirect(current_user)
      end
    end
  end

  def creare
    @blog = Blog.new(blog_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @blogs = Blog.all
    @blog.user_id = current_user.id
    if @blog.save #入力されたデータをdbに保存する。
      redirect_to blog_path(@blog), notice: "successfully created book!"#保存された場合の移動先を指定。
    else
      @user = current_user
      render 'index'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user! , only:[:edit, :show, :confirm]

  def new
  	@user = User.new
  end

  def index
    @users = User.all.page(params[:page]).per(5)
    @user = User.find(current_user.id)
    @blog = Blog.new
  end

  def show
    @user = User.find(params[:id])
    @blogs = @user.blogs
  end

  def edit
    @user = User.find(params[:id])
      if current_user.id != @user.id
      redirect_to edit_user_path(current_user)
      end
  end

  def update
    @user = User.find(params[:id])
    if params[:status] == "false"
      @user.update_columns(status: false)
      sign_out_and_redirect(current_user)
    else
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to user_path(@user.id)
      else
        render :edit
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :introduction, :telephone, :password, :status, :profile_image)
  end

end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_comments_helper.rb
module BlogCommentsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/blogs/edit.html.erb
<%= render "admin/home/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
		<h2>ブログ編集</h2>
			<div class="row">
				<div class="col-md-8 col-md-offset-1">
					<%= form_for @blog,url: admin_blog_path(@blog.id) do |f| %>

						<!-- エラーメッセージ表示-->
						<%= render "devise/shared/error_messages", resource: @blog %>
						<!-- エラーメッセージ表示-->

						<div class="row">
							<div class="col-md-5 col-md-offset-1">ブログタイトル</div>
							<div class="col-md-2"><%= f.text_field :title, class: "panel panel-default"  %></div>
						</div>

						<div class="row">
							<div class="col-md-5 col-md-offset-1">ブログ内容</div>
							<div class="col-md-2"><%= f.text_area :introduction, class: "panel panel-default"  %></div>
						</div>

						<div class="row">
							<div class="col-md-4 col-md-offset-1">メーカー</div>
							<div class="col-md-2"><%= f.collection_select :genre_id, Genre.all, :id, :name, class: "panel panel-default"  %></div>
						</div>

						<div class="row">
					      <div class="col-md-5 col-md-offset-1">ブログ写真</div>
					        <div class="col-md-2"><%= f.attachment_field :image, class: "blog_image" %>
					        <%= attachment_image_tag(@blog, :image, :fill, 100, 100, fallback: "no_image.jpg") %></div>
					    </div>

					    <div class="row">
							<%= f.submit class: "btn btn-primary col-md-6 col-md-offset-2" %>
						</div>

					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admin/blogs/index.html.erb
<%= render "admin/home/header" %>


<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
			<h3>ブログ一覧画面</h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<table class="table">
						<tr>
							<th>ブログID</th>
							<th>氏名</th>
							<th>タイトル</th>
							<th>紹介文</th>
							<th>画像</th>

						</tr>
					<tbody class="table-box">
						<% @blogs.each do |blog| %>
							<tr>
								<td><%= blog.id %></td>
								<td><%= link_to blog.user.name, admin_user_path(blog.user.id) %></td>
								<td><%= blog.title %></td>
								<td><%= blog.introduction %></td>
								<td><%= attachment_image_tag(blog, :image, :fill, 100, 100, fallback: "no_image.jpg") %></td>
								<td><%= link_to "編集", edit_admin_blog_path(blog.id), class: "btn btn-primary" %></td>


							</tr>
						<% end %>
					</tbody>
			</table>

			<div class="paginate">
      			<%= paginate @blogs %>
    		</div>

		</div>
	</div>

</div>

app/views/admin/blogs/show.html.erb
<%= render 'admin/home/header' %>

<div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">

        <h3 class="title">ブログ詳細画面</h3>

        <div class="row text">
          <div class="col-md-2">ブログID</div>
          <div class="col-md-10"><%= @blog.id %>

        <div class="row text">
          <div class="col-md-2">氏名</div>
          <div class="col-md-10"><%= @user.name %></div>
        </div>

        <div class="row text">
          <div class="col-md-2">タイトル</div>
          <div class="col-md-1"><%= @blog.title %></div>
        </div>

        <div class="row text">
          <div class="col-md-2">紹介文</div>
          <div class="col-md-1"><%= @blog.introduction %></div>
        </div>

        <div class="row text">
          <div class="col-md-2">画像</div>
          <div class="col-md-1"><%= @blog.image %></div>
        </div>

      </div>
  </div>
<div>

app/views/blogs/edit.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
		<h2>ブログ編集</h2>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<%= form_for(@blog) do |f| %>

				<!-- エラーメッセージ表示-->
				     <% if @blog.errors.any? %>
				       <%= @blog.errors.count %>error prohibited this obj from being saved
				       <%= @blog.errors.full_messages.each do |message| %>
				         <%= message %>
				       <% end %>
				     <% end %>

				<!-- エラーメッセージ表示-->

						<div class="row">
							<div class="col-md-4 col-md-offset-1">ブログタイトル</div>
							<div class="col-md-2"><%= f.text_field :title, class: "panel panel-default"  %></div>
						</div>

						<div class="row">
							<div class="col-md-4 col-md-offset-1">ブログ内容</div>
							<div class="col-md-2"><%= f.text_area :introduction, class: "panel panel-default"  %></div>
						</div>

						<div class="row">
							<div class="col-md-4 col-md-offset-1">メーカー</div>
							<div class="col-md-2"><%= f.collection_select :genres_id, Genre.all, :id, :name, class: "panel panel-default"  %></div>
						</div>

						<div class="row">
					      <div class="col-md-5 col-md-offset-1">ブログ写真</div>
					        <div class="col-md-2"><%= f.attachment_field :image, class: "blog_image" %>
					        <%= attachment_image_tag(@blog, :image, :fill, 100, 100, fallback: "no_image.jpg") %></div>
					    </div>

					    <div class="row">
							<%= f.submit class: "btn btn-primary col-md-6 col-md-offset-2" %>
						</div>

					<% end %>

					<div class="col-md-6 col-md-offset-1">
						<%= link_to "詳細", @blog, class: "blog_#{@blog.id}" %>
						<%= link_to "戻る", blogs_path, class: "back" %>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>

app/views/blogs/index.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-7 col-md-offset-2">
			<h2>投稿一覧</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>タイトル</th>
						<th>紹介文</th>
						<th></th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @blogs.each do |blog| %>
					<tr>
						<td>
							<%= link_to user_path(blog.user) do %>
							<%= attachment_image_tag blog.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no-image-mini.jpg" %>
							<% end %>
						</td>
						<td><%= link_to blog.title, blog, class: "blog_#{blog.id}" %></td>

						<td><%= blog.introduction %></td>

						<td>
							<% if blog.favorited_by?(current_user) %>
							    <%= link_to blog_favorites_path(blog),class: 'glyphicon glyphicon-heart', method: :delete do %>
							    	<i class="fa fa-heart" aria-hidden="true" style="color: black;"></i>
							    	<%= blog.favorites.count %>
							    <% end %>
							<% else %>
							    <%= link_to blog_favorites_path(blog),class: 'glyphicon glyphicon-heart', method: :post do %>
							    	<i class="fa fa-heart-o" aria-hidden="true"></i>
							    	<%= blog.favorites.count %>
								<% end %>
							<% end %>
						</td>
						<td>
						    <i class="comment-count">コメント数：<%= @blog.blog_comments.count %></i>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<div class="paginate">
    			<%= paginate @blogs %>
    		</div>
		</div>
	</div>
</div>

app/views/blogs/new.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-2">
			<h2>ブログ投稿</h2>
			<%= form_for(@blog) do |f| %>

				<!-- エラーメッセージ表示-->
				<% if @blog.errors.any? %>
				    <%= @blog.errors.count %>error prohibited this obj from being saved
				    <%= @blog.errors.full_messages.each do |message| %>
				    	<%= message %>
				    <% end %>
				<% end %>

				<!-- エラーメッセージ表示-->

				<div class="row">
					<div class="col-md-4 col-md-offset-1">ブログタイトル</div>
					<div class="col-md-2"><%= f.text_field :title, class: "panel panel-default"  %></div>
				</div>

				<div class="row">
					<div class="col-md-4 col-md-offset-1">ブログ内容</div>
					<div class="col-md-2"><%= f.text_area :introduction, class: "panel panel-default"  %></div>
				</div>

				<div class="row">
					<div class="col-md-4 col-md-offset-1">メーカー</div>
					<div class="col-md-2"><%= f.collection_select :genre_id, Genre.all, :id, :name, class: "panel panel-default"  %></div>
				</div>

				<div class="row">
			      <div class="col-md-5 col-md-offset-1">ブログ写真</div>
			        <div class="col-md-2"><%= f.attachment_field :image, class: "user_image" %></div>
			    </div>

				<div class="row">
					<%= f.submit class: "btn btn-primary col-md-10" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/blogs/show.html.erb
<%= render "users/header" %>

<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h2>詳細ページ</h2>
			<table class="table">

				<thead>
					<tr>
						<th></th>
						<th></th>
						<th>タイトル</th>
						<th>紹介文</th>
						<th>メーカー</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tr>
					<td class="col-md-1 col-md-offset-4">
						<%= attachment_image_tag(@blog.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					</td>

					<td class="col-md-1 col-md-offset-3 ">
					    <%= attachment_image_tag(@blog, :image, :fill, 200, 200, fallback: "no_image.jpg", size:'100x100' ) %>
					</td>

					<td class="col-md-2 col-md-offset-4"><%= link_to @blog.title, blog_path(@blog) %></td>

					<td class="col-md-3 col-md-offset-4"><%= @blog.introduction %></td>

					<td class="col-md-2 col-md-offset-4"><%= @genre.name %></td>

					<td>
						<% if @blog.favorited_by?(current_user) %>
						    <%= link_to blog_favorites_path(@blog),class: 'glyphicon glyphicon-heart', method: :delete do %>
						      <i class="fa fa-heart " aria-hidden="true" style="color: black;"></i>
						      <%= @blog.favorites.count %>
						    <% end %>
						<% else %>
						    <%= link_to blog_favorites_path(@blog),class: 'glyphicon glyphicon-heart', method: :post do %>
						      <i class="fa fa-heart-o" aria-hidden="true"></i>
						      <%= @blog.favorites.count %>
						    <% end %>
						<% end %>
					</td>
					<% if current_user == @blog.user %>
						<td class="col-md-1 col-md-offset-3"><%= link_to "編集",edit_blog_path(@blog), class: "btn-sm btn-success edit_blog_#{@blog.id}" %></td>
						<td class="col-md-1 col-md-offset-2"><%= link_to "削除",@blog, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_blog_#{@blog.id}" %></td>
					<% end %>
				</tr>
			</table>
			<div class="row">
				<div class="col-md-6 col-md-offset-1" style="margin-top: 20px;">

					<% @blog.blog_comments.each do |blog| %>
                	    <%= attachment_image_tag blog.user, :profile_image, :fill, 60, 60, fallback: "no-image-mini.jpg" %>

						<div class="row">
							<div class="col-md-4 col-md-offset-1">名前：</div>
							<div class="col-md-5 col-md-offset-1">
                                <a href="#" class="link-author col-md-4 col-md-offset-1"><%= blog.user.name %></a>
							</div>
						</div>

						<div class="row">
							<div class="col-md-4 col-md-offset-1">コメント：</div>
							<div class="col-md-2"><%= blog.comment %></div>
						</div>

						<div class="row">
							<div class="col-md-4 col-md-offset-1">日付</div>
							<div class="col-md-2"><%= blog.created_at.strftime('%Y/%m/%d') %></div>
						</div>

                	<% end %>
				</div>
			</div>

			   	<div class="section-title-wrapper style-1 v1 mt-30" id="divAddComment">
			   	    <h3 class="section-title left"><span>コメント</span></h3>
			   	</div>
			   	<%= form_for [@blog, @blog_comment] do |f| %>
			   	    <div class="row">
			   	        <div class="col-sm-12">
			   	            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			   	        </div>
			   	    </div>
			   	    <%= f.submit "送信する", class: "btn-sm btn-primary pull-right" %>
			   	<% end %>
			</div>
		</div>
	</div>
</div>